Adicionado um botao e a mensagem  "Seu carrinho está vazio"
tryber/sd-07-project-frontend-online-store pull request #138
Opened 2020-11-24 22:03 UTC by PedroMarqdev

Foi adicionado ao componente ProductList um botão e um elemento de texto com a mensagem "Seu carrinho está vazio" 
Há a ideia de criar também um componente para botões caso seja preciso.

2020-11-24 22:33 UTC, thalysmcarrara approved these changes
eslint ok, só bora!

2020-11-25 01:38 UTC, gabrieldeori approved these changes

2020-11-25 01:39 UTC, thalysmcarrara approved these changes

2020-11-25 01:44 UTC, ThiagoPederzolli requested changes
A ideia é um fluxo de páginas.
O botão deveria direcionar para uma nova página que será a responsável pelo carrinho de compras da pessoa usuária, logo, o texto "Seu carrinho está vazio" deve ser presente em um outro componente que será renderizado após o redirecionamento da pessoa que clicar no link para o carrinho de compras.

2020-11-25 14:09 UTC, ThiagoPederzolli approved these changes

2020-11-25 14:10 UTC, merged