[GRUPO 24 - Tropa de ESLint] Resolvendo Requisito 06
tryber/sd-07-project-frontend-online-store pull request #320
Opened 2020-11-25 22:40 UTC by rafaelmguimaraes

2020-11-25 23:12 UTC, FernandoAntunesFilho requested changes
Fiz apenas 1 comentário pra revisão, caso faça sentido pra você.

2020-11-25 23:12 UTC, FernandoAntunesFilho commented on src/CategoriesList.jsx
>    async fetchCategories() {
Que tal declarar a função antes de chama-la no 'componentDidMount'?
Fica mais claro declarar e depois chamar.

2020-11-25 23:15 UTC, rafaelmguimaraes commented on src/CategoriesList.jsx
>    async fetchCategories() {
Vc tem razão, mas foi uma reclamação do ESLint rs vai entender

2020-11-25 23:19 UTC, Demistocles approved these changes

2020-11-26 05:27 UTC, vagnerpsousa approved these changes
ok!

2020-11-26 14:17 UTC, merged